# Generated by Django 5.2.3 on 2025-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='stock',
            field=models.IntegerField(default=False, verbose_name='Online Availability'),
        ),
    ]
